// leave off @2x/@3x
const images = {
  logo: require('../Images/ir.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  shield: require('../Images/account.png'),
  mapMarkerUser: require('../Images/Icons/map-marker-user.png'),
  mapMarkerStore: require('../Images/Icons/map-marker-store.png'),
  gunadarma: require('../Images/gunadarma.png'),
  social: {
    bbm: require('../Images/Socials/bbm.png'),
    beetalk: require('../Images/Socials/beetalk.png'),
    // behance: require('../Images/Socials/behance.png'),
    blog: require('../Images/Socials/blog.png'),
    // dropbox: require('../Images/Socials/dropbox.png'),
    email: require('../Images/Socials/email.png'),
    facebook: require('../Images/Socials/facebook.png'),
    // feed: require('../Images/Socials/feed.png'),
    // flikr: require('../Images/Socials/flikr.png'),
    googleplus: require('../Images/Socials/googleplus.png'),
    instagram: require('../Images/Socials/instagram.png'),
    line: require('../Images/Socials/line.png'),
    linkedin: require('../Images/Socials/linkedin.png'),
    path: require('../Images/Socials/path.png'),
    phone: require('../Images/Socials/phone.png'),
    skype: require('../Images/Socials/skype.png'),
    snapchat: require('../Images/Socials/snapchat.png'),
    // sound_cloud: require('../Images/Socials/sound_cloud.png'),
    twitter: require('../Images/Socials/twitter.png'),
    // vimeo: require('../Images/Socials/vimeo.png'),
    weechat: require('../Images/Socials/weechat.png'),
    whatsapp: require('../Images/Socials/whatsapp.png'),
    // wordpress: require('../Images/Socials/wordpress.png'),
    yahoo: require('../Images/Socials/yahoo.png'),
    youtube: require('../Images/Socials/youtube.png')
  },
  rating: {
    starFilled: require('react-native-rating/assets/star_filled.png'),
    starUnfilled: require('react-native-rating/assets/star_unfilled.png')
  }
}

export default images
